package game.AI;

public enum AiTypes {
    CFR_CLUSTERING,
    MCCFR,
    RULE_BASED,
    BASIC_MCTS_CHEATING_PI_GAME_SIM_UCB1,
    BASIC_MCTS_CHEATING_PI_GAME_SIM_UCT,
    BASIC_MCTS_CHEATING_PI_ROUND_SIM_UCB1,
    Cheating_MCTS, //BASIC_MCTS_CHEATING_PI_ROUND_SIM_UCT
    PIMC, //PIMC_ROUND_SIM_UCT
    SO_ISMCTS,
    MO_ISMCTS,
    DeepCFR,
    ISMCTSANN;
}
